# Generated by Django 4.1.7 on 2023-04-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalali', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
